package com.atama.dto.game;

import lombok.Data;

@Data
public class GameJoinRequest {
    private String joinCode;
    private String nickname;
    private String participantId; // generated by frontend or uses userId
}
