spring.application.name=Atama

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-cold-sky-aitsa265.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5W3nSsXiIdhl
#spring.datasource.url=jdbc:postgresql://localhost:5432/atama
#spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=atamacs307@gmail.com
spring.mail.password=jikm zdza fpwq xelj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
