package com.atama.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

@Entity
@DiscriminatorValue("CONCEPT_MAP")
@Getter
@Setter
public class ConceptMap extends LibraryItem {

    /** JSON blob: { "nodes": [...], "edges": [...] } generated by Gemini */
    @Column(columnDefinition = "TEXT")
    private String graphData;

    /** Path to the server-side rendered PNG saved in uploads/ */
    @Column
    private String pngPath;

    /** The flashcard set this map was originally generated from (can be null if cross-set) */
    @Column
    private UUID sourceSetId;
}
